import './languageToggle';
import './mobile-menu';
import './client-office/pageHeaderShowMenu';
import './client-office/mobileMenuPrivate';
import './client-office/switchBetweenListAndCalendar';
// import './client-office/modalUserInformation';
import './client-office/modalInformationDepartment';
import './client-office/modalReminder';
import './client-office/menuNavigation';
import './client-office/myCustomersSwitchButton';
// import './client-office/articlesAndWebinarsSwitch';
import './client-office/clientsListOpenRecords';
import './client-office/logout';
import './client-office/checkLoggedIn';
