import './mobile-menu';
import './languageToggle';
import './tests/tests';
import './tests/selectionPsychologistClient';
import './tests/card-slider';
// import './tests/dropDownMenu';
import './private-office/modalInformationDepartment';
import './private-office/modalReminder';
import './checkLoggedIn';
import './private-office/outsidePrivateOffice';
import './private-office/outsideMenuNavigation';
import './client-office/outsideMenuNavigation';
import './outsideLogout';
