import ourTeam1Mobil2x from '../../images/our-team-mobil@2x.jpg';
import ourTeam1Tablet2x from '../../images/our-team-tablet@2x.jpg';
import ourTeam1Desktop2x from '../../images/our-team-desktop@2x.jpg';

import ourTeam2Mobil2x from '../../images/ourTeam2Mobil2x.jpg';
import ourTeam2Tablet2x from '../../images/ourTeam2Tablet2x.jpg';
import ourTeam2Desktop2x from '../../images/ourTeam2Desktop2x.jpg';

import ourTeam3Mobil2x from '../../images/ourTeam3Mobil2x.jpg';
import ourTeam3Tablet2x from '../../images/ourTeam3Tablet2x.jpg';
import ourTeam3Desktop2x from '../../images/ourTeam3Desktop2x.jpg';

import ourTeam4Mobil2x from '../../images/ourTeam4Mobil2x.jpg';
import ourTeam4Tablet2x from '../../images/ourTeam4Tablet2x.jpg';
import ourTeam4Desktop2x from '../../images/ourTeam4Desktop2x.jpg';

import HelloImg from '../../images/Hello.png';

export const teamMembers = [
  {
    id: '1',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 1,
    specialties: [
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '2',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 2,
    specialties: [
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '3',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 3,
    specialties: [
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '4',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 4,
    specialties: [
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '5',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 5,
    specialties: [
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '6',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 6,
    specialties: [
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '7',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 7,
    specialties: [
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '8',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 8,
    specialties: [
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '9',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 9,
    specialties: ['family', 'Наші стосунки зайшли у глухий кут'],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '10',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 10,
    specialties: [
      'family',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '11',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 11,
    specialties: [
      'family',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '12',
    name: 'Іван Виговський',
    gender: 'male',
    therapys: ['особиста', 'парна'],
    languages: ['українська', 'російська'],
    experience: '3 роки практики',
    experienceValue: 12,
    specialties: [
      'family',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 430,
    priceRange: '400-799',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam1Desktop2x} 1x, ${ourTeam1Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam1Tablet2x} 1x, ${ourTeam1Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam1Mobil2x} 1x, ${ourTeam1Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam1Mobil2x,
    alt: 'Фото Іван Виговський',
  },
  {
    id: '13',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: [
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
    ],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '14',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: [
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
    ],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '15',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: [
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Старші підлітки',
    ],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '16',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: [
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
    ],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '17',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: [
      'child',
      'Малята',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
    ],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '18',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: [
      'child',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
    ],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '19',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: [
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
    ],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '20',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: ['child', 'Малята', 'Молодший дошкільний вік'],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '21',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: ['child', 'Малята'],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '22',
    name: 'Марія Оса',
    gender: 'female',
    therapys: ['парна', 'Дитяча'],
    languages: ['українська', 'англійська'],
    experience: '12 років практикиx',
    experienceValue: 12,
    specialties: ['child', 'Старші підлітки'],
    priceValue: 850,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: false,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam2Desktop2x} 1x, ${ourTeam2Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam2Tablet2x} 1x, ${ourTeam2Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam2Mobil2x} 1x, ${ourTeam2Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam2Mobil2x,
    alt: 'Фото Марія Оса',
  },
  {
    id: '23',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '24',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '25',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '26',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '27',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '28',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '29',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '30',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '31',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '32',
    name: 'Олег Марʼяненко',
    gender: 'male',
    therapys: ['особиста', 'парна', 'Дитяча'],
    languages: ['українська', 'англійська', 'російська'],
    experience: '5 років практики',
    experienceValue: 5,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
    ],
    priceValue: 1300,
    priceRange: '1200+',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: true,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam3Desktop2x} 1x, ${ourTeam3Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam3Tablet2x} 1x, ${ourTeam3Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam3Mobil2x} 1x, ${ourTeam3Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam3Mobil2x,
    alt: 'Фото Олег Марʼяненко',
  },
  {
    id: '33',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
  {
    id: '34',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
  {
    id: '35',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
  {
    id: '36',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
  {
    id: '37',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
  {
    id: '38',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
  {
    id: '39',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
  {
    id: '40',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
  {
    id: '41',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
  {
    id: '42',
    name: 'Карина Вайн',
    gender: 'female',
    therapys: ['особиста', 'Дитяча'],
    languages: ['українська'],
    experience: '10 років практикиx',
    experienceValue: 10,
    specialties: [
      'myself',
      'Мій настрій різко змінюється',
      'Я швидко втомлююся',
      'Мене нічого не радує',
      'Я не можу/не хочу нічого робити',
      'Мені важко зосередитися',
      'Я постійно перебуваю у напруженому стані',
      'У мене часто з‘являються тривожні думки',
      'Я погано себе почуваю',
      'Мені складно спілкуватися з іншими людьми',
      'Я не задоволений(на) собою',
      'Я відчуваю себе нещасним(ою)',
      'Депресія, стрес',
      'Панічні атаки',
      'Підвищена тривожність',
      'Проблеми зі сном',
      'Емоційне вигорання',
      'Залежність (алкогольна, наркотична, ігрова і т.д.)',
      'Тяжке захворювання',
      'Розлад харчової поведінки',
      'Хронічні болі',
      'Психосоматика',
      'child',
      'Малята',
      'Молодший дошкільний вік',
      'Молодший шкільний вік',
      'Молодші підлітки',
      'Старші підлітки',
      'family',
      'Наші стосунки зайшли у глухий кут',
      'Розлучаємося. Потребуємо підтримки',
      'У наших стосунках зрада',
      'Я ревную/мене ревнують',
      'Маємо проблему у сексуальному житті',
      'У нас фінансові труднощі',
      'Сперечаємося щодо виховання дітей',
      'Стосунки на відстані. Маємо складнощі',
      'Плануємо вагітність/ пологи',
    ],
    priceValue: 1000,
    priceRange: '800-1199',
    priceUnit: 'грн/час',
    iconSrc: HelloImg,
    status: true,
    friendly: false,
    photoSources: [
      {
        media: '(min-width: 1280px)',
        srcset: `${ourTeam4Desktop2x} 1x, ${ourTeam4Desktop2x} 2x`,
      },
      {
        media: '(min-width: 744px)',
        srcset: `${ourTeam4Tablet2x} 1x, ${ourTeam4Tablet2x} 2x`,
      },
      {
        media: '(max-width: 743px)',
        srcset: `${ourTeam4Mobil2x} 1x, ${ourTeam4Mobil2x} 2x`,
      },
    ],
    photoSrc: ourTeam4Mobil2x,
    alt: 'фото Карина Вайн',
  },
];
